name: Custom smoke test

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
      with:
        python-version: '3.11'

    - name: test
      run: |
        echo ok
