name: Deploy to GCS

inputs:
  gcp_workload_identity_provider:
    description: "Google Cloud workload identity provider"
    required: true
  gcp_service_account:
    description: "Google Cloud service account name"
    required: true
  timestamp_only:
    description: "If 'true', deployment will not happen if there are changes other than timestamp"
    required: false
    default: 'false'
outputs:
  deployed:
    description: "'true' if a timestamp-only deployment did the deployment"
    value: ${{ steps.timestamp-deploy.outputs.deployed }}

runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@c850b930e6ba138125429b7e5c93fc707a7f8427 # v4.1.4
      with:
        name: github-pages

    - uses: google-github-actions/auth@a6e2e39c0a0331da29f7fd2c2a20a427e8d3ad1f # v2.1.1
      with:
        token_format: 'access_token'
        workload_identity_provider: ${{ inputs.gcp_workload_identity_provider }}
        service_account: ${{ inputs.gcp_service_account }}

    - uses: google-github-actions/setup-gcloud@98ddc00a17442e89a24bbf282954a3b65ce6d200 # v2.1.0

    - name: Deploy timestamp to GCS (if there are no other changes)
      if: inputs.timestamp-only == 'true'
      id: timestamp-deploy
      shell: bash
      run: |
        BUCKET="gs://jku-testbucket/"

        # Extract the github-pages archive into ./repository/
        mkdir repository
        tar --directory repository -xvf artifact.tar

        # download current content
        gcloud storage rsync --recursive $BUCKET current-repository

        # Test what the changes would be if we exclude timestamp
        rsync --recursive current-repository/ new-repository/
        rsync --recursive --exclude=metadata/timestamp.json repository/ new-repository/
        if diff --brief --recursive current-repository new-repository; then
            echo No changes detected outside of timestamp: deploying timestamp.json
            gcloud storage cp --cache-control=no-store repository/metadata/timestamp.json ${BUCKET}metadata/timestamp.json
            echo "deployed=true" >> "$GITHUB_OUTPUT"
        else
            echo Full repository deployment needed
            echo "deployed=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Deploy full repository to GCS
      if: inputs.timestamp-only != 'true'
      shell: bash
      run: |
        BUCKET="gs://jku-testbucket/"

        # Extract the github-pages archive into ./repository/
        mkdir repository
        tar --directory repository -xvf artifact.tar

        # Upload metadata, make sure we upload timestamp last
        gcloud storage rsync --checksums-only --cache-control=no-store --recursive --exclude=timestamp.json \
            repository/ $BUCKET
        gcloud storage cp --cache-control=no-store repository/metadata/timestamp.json ${BUCKET}metadata/timestamp.json    
