name: Custom repository tests

on:
  workflow_call:

permissions: {}

jobs:
  custom-test:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea
        with:
          script: |
            console.log(github.rest)
            console.log(github.rest.graphql)

      - run: |
          echo "CUSTOM TEST: OK"
          echo GITHUB_WORKFLOW_REF $GITHUB_WORKFLOW_REF
