name: Custom repository tests

on:
  workflow_call:

permissions: {}

jobs:
  custom-test:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - run: |
          echo "CUSTOM TEST: OK"
          echo GITHUB_WORKFLOW_REF $GITHUB_WORKFLOW_REF
