name: Deploy repository to GCS

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      gcp_workload_identity_provider:
        required: true
        type: string
      gcp_service_account:
        required: true
        type: string

permissions: {}

jobs:
  deploy-to-gcs:
    runs-on: ubuntu-latest
    permissions:
      id-token: 'write' # For authenticating with the GitHub workflow identity

    steps:
      - uses: google-github-actions/auth@a6e2e39c0a0331da29f7fd2c2a20a427e8d3ad1f # v2.1.1
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/843741030650/locations/global/workloadIdentityPools/testpool/providers/testprovider'
          service_account: 'testsa@python-tuf-kms.iam.gserviceaccount.com'
          create_credentials_file: true
      - uses: google-github-actions/setup-gcloud@98ddc00a17442e89a24bbf282954a3b65ce6d200 # v2.1.0
        #with:
        #  project_id: project-rekor

      ## Unclear why this is needed?
      #- name: Login
      #  run: |
      #    gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
      #    gcloud auth list

      - uses: actions/download-artifact@eaceaf801fd36c7dee90939fad912460b18a1ffe # v4.1.2
        with:
          name: github-pages
          path: repository

      - run: |
          cd repository
          tar xvf artifact.tar
          rm artifact.tar

          ls -ltr *

          gcloud storage cp --cache-control=no-store -r ./ gs://jku-testbucket/