name: TUF-on-CI signing event

permissions: {}

on:
  workflow_dispatch:
  push:
    branches: ['sign/**']
    paths: ['metadata/**', 'targets/**']

jobs:
  handle-signing-event:
    name: TUF-on-CI signing event
    runs-on: ubuntu-latest
    permissions:
      contents: write # for making git commits in branch and setting draft state on/off
      pull-requests: write
      actions: write # for dispatching another signing-event workflow

    steps:
      - name: Signing event
        uses: theupdateframework/tuf-on-ci/actions/signing-event@main # Test using PRs instead of Issues
        with:
          token: ${{ secrets.TUF_ON_CI_TOKEN || secrets.GITHUB_TOKEN }}
