name: TUF-on-CI repository tests

on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: '17 4,10,16,22 * * *'

permissions: {}

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - name: Smoke test repository with a client
        uses: jku/tuf-on-ci/actions/test-repository@issue-mgmt # FIXME repo & ref

  update-issue:
    runs-on: ubuntu-latest
    needs: [smoke-test]
    # During workflow_call, caller updates issue
    if: always() && !cancelled() && github.workflow == 'test.yml'
    permissions:
      issues: 'write' # for modifying Issues
    steps:
      - name: Update the issue for the workflow
        uses: jku/tuf-on-ci/actions/update-issue@issue-mgmt # FIXME repo & ref
        with:
          token: ${{ secrets.TUF_ON_CI_TOKEN || secrets.GITHUB_TOKEN }}
          success: ${{ !contains(needs.*.result, 'failure') }}
